/**
 * GET /api/design/master-components?category=<cat>
 *
 * Server-side proxy to the Ottomate tracker. Returns the catalog entries for a category.
 * Token stays here, never reaches the browser.
 *
 * Generated by Ottomate skill scaffold.
 */
import { NextRequest, NextResponse } from "next/server";
import { getMasterComponentsByCategory } from "@/lib/design/tracker";

export async function GET(req: NextRequest) {
  const category = req.nextUrl.searchParams.get("category");
  if (!category) {
    return NextResponse.json({ error: "missing required query param: category" }, { status: 400 });
  }
  try {
    const master = await getMasterComponentsByCategory(category);
    return NextResponse.json({ master_components: master });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
