ALTER TABLE `questions` ADD `editorial_note_2` text;--> statement-breakpoint
UPDATE `questions` SET `editorial_note` = 'Gabbar and Mogambo trade the crown by decade — but Crime Master Gogo never leaves the podium.', `editorial_note_2` = 'Younger voters rate the comic villains higher; the old guard still fears the menace.' WHERE `id` = 'NEW-205';--> statement-breakpoint
UPDATE `questions` SET `editorial_note` = 'Mumbai and Delhi split the country down the middle; Indore punches far above its size.', `editorial_note_2` = 'Kolkata''s vote is loud but local — it wins its own state by a landslide, less elsewhere.' WHERE `id` = 'NEW-206';--> statement-breakpoint
UPDATE `questions` SET `editorial_note` = 'Filter coffee owns the south; chai takes the rest — the one cup the country will not agree on.', `editorial_note_2` = '"Just water" over-indexes with the under-25s. Make of that what you will.' WHERE `id` = 'NEW-209';--> statement-breakpoint
UPDATE `questions` SET `editorial_note` = 'Dishes top the dread list nationally — but cooking splits sharply by who does it.', `editorial_note_2` = 'The people who say they do not mind ironing are a small, suspicious minority.' WHERE `id` = 'NEW-213';--> statement-breakpoint
UPDATE `questions` SET `editorial_note` = 'Big-city voters keep the metro; everyone else keeps the lake.', `editorial_note_2` = 'The split barely moves with age — this one is about where you live, not how old you are.' WHERE `id` = 'NEW-211';--> statement-breakpoint
UPDATE `questions` SET `editorial_note` = '3 Idiots is the safest rewatch in the country; RRR splits the room.', `editorial_note_2` = 'DDLJ''s yes-vote climbs with age — Gully Boy''s falls.' WHERE `id` = 'NEW-216';--> statement-breakpoint
UPDATE `questions` SET `editorial_note_2` = 'The podium reshuffles by region, but the top three never change.' WHERE `id` = 'NEW-92';--> statement-breakpoint
UPDATE `questions` SET `editorial_note_2` = 'Nimbu paani spikes in the summer months — a seasonal vote if there ever was one.' WHERE `id` = 'NEW-93';
