/**
 * POST /api/design/skip
 *
 * Body: { component_id: number, skip_reason: string }
 *
 * Server-side proxy that round-trips the skip to the tracker with bearer auth.
 *
 * Generated by Ottomate skill scaffold.
 */
import { NextRequest, NextResponse } from "next/server";
import { skipComponent } from "@/lib/design/tracker";

export async function POST(req: NextRequest) {
  let body: { component_id?: number; skip_reason?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json body" }, { status: 400 });
  }
  const { component_id, skip_reason } = body;
  if (typeof component_id !== "number" || !skip_reason || skip_reason.trim().length < 3) {
    return NextResponse.json(
      { error: "missing required fields: component_id (number), skip_reason (non-trivial string)" },
      { status: 400 }
    );
  }
  try {
    const result = await skipComponent(component_id, skip_reason);
    return NextResponse.json(result);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
