/**
 * Server-side helper for talking to the Ottomate tracker API.
 *
 * Reads TRACKER_API_BASE + TRACKER_API_TOKEN from env. NEVER imported by client code —
 * keep the token off the browser. All calls from /design's client components go through
 * the local /api/design/* routes which then call this helper.
 *
 * Generated by Ottomate skill scaffold (data/scaffold/design-route/). Do not edit by hand
 * unless the corresponding skill template has been updated.
 */

const DEFAULT_BASE = "http://192.168.1.10:8110";

export type ComponentRow = {
  id: number;
  page_id: string;
  project_slug: string;
  name: string;
  purpose_on_page: string | null;
  category: string | null;
  picked: 0 | 1;
  asset_library_ref: string | null;
  skip_reason: string | null;
  picked_variant: string | null;
  current_phase: string;
};

export type MasterComponent = {
  id: string;
  name: string;
  category: string;
  description: string | null;
  source_code_path: string | null;
  primary_file: string | null;
  framework_tags: string[] | null;
  tags: string[] | null;
  dependencies: string[] | null;
  variants_json: string[] | null;
  preview_url: string | null;
  license_note: string | null;
};

export type UIMasterPlan = {
  project_slug: string;
  aspect_ratios: string[] | null;
  palette_dark: Record<string, string> | null;
  palette_light: Record<string, string> | null;
  fonts: { heading?: string; body?: string; mono?: string } | null;
  animation_level: string | null;
  layout_style: string | null;
};

export type Page = {
  id: string;
  title: string;
  route: string;
  layout_type: string | null;
};

export type DesignContext = {
  project: {
    slug: string;
    display_name: string;
  };
  ui_master_plan: UIMasterPlan;
  components: ComponentRow[];
  pages: Page[];
};

function trackerBase(): string {
  return process.env.TRACKER_API_BASE || DEFAULT_BASE;
}

function trackerToken(): string {
  const t = process.env.TRACKER_API_TOKEN;
  if (!t) {
    throw new Error(
      "TRACKER_API_TOKEN is not set on the server. /design write actions require this env var. " +
        "Read the token from /opt/homeserver/ottomate/.token on VAULT7A and inject via docker-compose."
    );
  }
  return t;
}

function projectSlug(): string {
  const s = process.env.OTTOMATE_PROJECT_SLUG;
  if (!s) {
    throw new Error(
      "OTTOMATE_PROJECT_SLUG is not set. /design needs to know which project it belongs to. " +
        "Set it in docker-compose.yml env: OTTOMATE_PROJECT_SLUG=<this-project-slug>."
    );
  }
  return s;
}

export async function getDesignContext(): Promise<DesignContext> {
  const slug = projectSlug();
  const url = `${trackerBase()}/api/projects/${slug}/context-packet?include=ui_master_plan,components,pages`;
  const res = await fetch(url, {
    headers: { Accept: "application/json" },
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error(`getDesignContext: tracker returned ${res.status} for ${url}`);
  }
  const json = await res.json();
  return {
    project: { slug: json.project.slug, display_name: json.project.display_name },
    ui_master_plan: json.ui_master_plan ?? {
      project_slug: slug,
      aspect_ratios: null,
      palette_dark: null,
      palette_light: null,
      fonts: null,
      animation_level: null,
      layout_style: null,
    },
    components: json.components ?? [],
    pages: json.pages ?? [],
  };
}

export async function getMasterComponentsByCategory(category: string): Promise<MasterComponent[]> {
  const url = `${trackerBase()}/api/master-components?category=${encodeURIComponent(category)}`;
  const res = await fetch(url, {
    headers: { Accept: "application/json" },
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error(`getMasterComponentsByCategory: tracker returned ${res.status} for ${url}`);
  }
  const json = await res.json();
  // Tracker returns { count, components: [...] } as of 2026-05-13.
  // Fall back to `master_components` for forward-compat if the shape changes.
  return (json.components ?? json.master_components ?? []) as MasterComponent[];
}

/**
 * Patch a component slot. Used for both pick (set asset_library_ref + picked=true) and
 * skip (set skip_reason). The tracker's PATCH /api/components/<id> accepts any subset of
 * ComponentPatchSchema (partial of ComponentCreateSchema).
 */
export async function patchComponent(
  componentId: number,
  patch: {
    picked?: boolean;
    asset_library_ref?: string | null;
    skip_reason?: string | null;
    picked_variant?: string | null;
  }
) {
  const url = `${trackerBase()}/api/components/${componentId}`;
  const res = await fetch(url, {
    method: "PATCH",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      Authorization: `Bearer ${trackerToken()}`,
    },
    body: JSON.stringify(patch),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`patchComponent: tracker returned ${res.status}: ${text}`);
  }
  return res.json();
}

export async function pickComponent(componentId: number, assetLibraryRef: string, variant?: string) {
  return patchComponent(componentId, {
    picked: true,
    asset_library_ref: assetLibraryRef,
    skip_reason: null,
    picked_variant: variant ?? null,
  });
}

export async function skipComponent(componentId: number, reason: string) {
  return patchComponent(componentId, {
    picked: false,
    asset_library_ref: null,
    skip_reason: reason,
  });
}
