"use client";

/**
 * /design — client island for slot grid + drawer + pick/skip actions.
 *
 * Reads server-provided components + pages, owns local UI state (selected slot, drawer
 * open, options fetch). Mutates via /api/design/pick and /api/design/skip — those proxy
 * to the tracker server-side so the bearer token stays out of the browser.
 *
 * Generated by Ottomate skill scaffold.
 */
import { useState, useMemo } from "react";

type Component = {
  id: number;
  page_id: string;
  project_slug: string;
  name: string;
  purpose_on_page: string | null;
  category: string | null;
  picked: 0 | 1;
  asset_library_ref: string | null;
  skip_reason: string | null;
  picked_variant: string | null;
  current_phase: string;
};

type Page = { id: string; title: string; route: string; layout_type: string | null };

type MasterComponent = {
  id: string;
  name: string;
  category: string;
  description: string | null;
  source_code_path: string | null;
  primary_file: string | null;
  framework_tags: string[] | null;
  tags: string[] | null;
  dependencies: string[] | null;
  variants_json: string[] | null;
  preview_url: string | null;
  license_note: string | null;
};

function statusOf(c: Component): "picked" | "skipped" | "pending" {
  if (c.picked === 1) return "picked";
  if (c.skip_reason) return "skipped";
  return "pending";
}

const statusColor: Record<ReturnType<typeof statusOf>, string> = {
  picked: "border-emerald-500/40 hover:border-emerald-500/60",
  skipped: "border-amber-500/30 hover:border-amber-500/50",
  pending: "border-rose-500/30 hover:border-rose-500/60",
};
const statusDot: Record<ReturnType<typeof statusOf>, string> = {
  picked: "bg-emerald-500",
  skipped: "bg-amber-500",
  pending: "bg-rose-500",
};

export function DesignClient({
  components,
  pages,
}: {
  components: Component[];
  pages: Page[];
}) {
  const [selectedSlotId, setSelectedSlotId] = useState<number | null>(null);
  const [filter, setFilter] = useState<"all" | "pending" | "picked" | "skipped">("all");
  const [localComponents, setLocalComponents] = useState(components);
  const pageMap = useMemo(() => Object.fromEntries(pages.map((p) => [p.id, p])), [pages]);

  const visible = useMemo(() => {
    if (filter === "all") return localComponents;
    return localComponents.filter((c) => statusOf(c) === filter);
  }, [localComponents, filter]);

  const grouped = useMemo(() => {
    const acc: Record<string, Component[]> = {};
    for (const c of visible) {
      const key = c.page_id;
      acc[key] = acc[key] || [];
      acc[key].push(c);
    }
    return acc;
  }, [visible]);

  const selected = selectedSlotId
    ? localComponents.find((c) => c.id === selectedSlotId) ?? null
    : null;

  function onMutate(updated: Component) {
    setLocalComponents((arr) => arr.map((c) => (c.id === updated.id ? updated : c)));
  }

  return (
    <>
      {/* Filter bar */}
      <div className="mb-4 flex flex-wrap gap-2 text-xs">
        {(["all", "pending", "skipped", "picked"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`rounded-full border px-3 py-1 capitalize transition-colors ${
              filter === f
                ? "border-[var(--accent-from,#6366f1)] bg-[var(--accent-from,#6366f1)]/10 text-[var(--fg,_#0f172a)]"
                : "border-[var(--border,_#e2e8f0)] text-[var(--fg-muted,_#64748b)] hover:border-[var(--accent-from,#6366f1)]/40"
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Slot grid grouped by page */}
      {pages.map((p) => {
        const slots = grouped[p.id] ?? [];
        if (slots.length === 0) return null;
        return (
          <div key={p.id} className="mb-6">
            <p className="mb-2 text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
              {p.title} <span className="opacity-60">· {p.route}</span>
            </p>
            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
              {slots.map((c) => {
                const s = statusOf(c);
                return (
                  <button
                    key={c.id}
                    onClick={() => setSelectedSlotId(c.id)}
                    className={`group relative overflow-hidden rounded-2xl border bg-[var(--bg-card,_var(--card,_#fff))] p-4 text-left transition-all duration-300 ${statusColor[s]}`}
                  >
                    <span
                      className="absolute top-0 right-6 left-6 h-[2px] rounded-full opacity-60 transition-opacity group-hover:opacity-100"
                      style={{
                        background: `linear-gradient(to right, var(--accent-from, #6366f1), var(--accent-to, #a855f7))`,
                      }}
                    />
                    <div className="flex items-center justify-between">
                      <span className="font-medium">{c.name}</span>
                      <span className={`size-2 rounded-full ${statusDot[s]}`} />
                    </div>
                    <p className="mt-1 text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
                      {c.category || "uncategorized"} · {s}
                    </p>
                    {c.purpose_on_page && (
                      <p className="mt-2 line-clamp-2 text-xs leading-relaxed text-[var(--fg-muted,_#64748b)]">
                        {c.purpose_on_page}
                      </p>
                    )}
                    {c.asset_library_ref && (
                      <p className="mt-2 truncate font-mono text-[10px] text-emerald-600 dark:text-emerald-400">
                        → {c.asset_library_ref}
                      </p>
                    )}
                    {c.skip_reason && (
                      <p className="mt-2 line-clamp-2 text-[10px] text-amber-600 dark:text-amber-400">
                        skipped: {c.skip_reason}
                      </p>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        );
      })}

      {selected && (
        <SlotDrawer
          slot={selected}
          page={pageMap[selected.page_id]}
          onClose={() => setSelectedSlotId(null)}
          onMutate={onMutate}
        />
      )}
    </>
  );
}

function SlotDrawer({
  slot,
  page,
  onClose,
  onMutate,
}: {
  slot: Component;
  page: Page | undefined;
  onClose: () => void;
  onMutate: (c: Component) => void;
}) {
  const [options, setOptions] = useState<MasterComponent[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [skipReason, setSkipReason] = useState("");

  useMemo(() => {
    let canceled = false;
    setLoading(true);
    setError(null);
    fetch(`/api/design/master-components?category=${encodeURIComponent(slot.category ?? "")}`)
      .then((r) => r.json())
      .then((j) => {
        if (canceled) return;
        if (j.error) setError(j.error);
        else setOptions(j.master_components ?? []);
      })
      .catch((e) => !canceled && setError(String(e)))
      .finally(() => !canceled && setLoading(false));
    return () => {
      canceled = true;
    };
  }, [slot.id, slot.category]);

  async function pick(option: MasterComponent, variant?: string) {
    setBusy(option.id);
    setError(null);
    try {
      const res = await fetch("/api/design/pick", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          component_id: slot.id,
          asset_library_ref: option.id,
          variant,
        }),
      });
      const j = await res.json();
      if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`);
      onMutate({ ...slot, picked: 1, asset_library_ref: option.id, picked_variant: variant ?? null, skip_reason: null });
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(null);
    }
  }

  async function skip() {
    if (skipReason.trim().length < 3) {
      setError("Skip reason needs at least 3 characters.");
      return;
    }
    setBusy("__skip__");
    setError(null);
    try {
      const res = await fetch("/api/design/skip", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ component_id: slot.id, skip_reason: skipReason }),
      });
      const j = await res.json();
      if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`);
      onMutate({ ...slot, picked: 0, skip_reason: skipReason, asset_library_ref: null });
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(null);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      <button
        aria-label="Close drawer"
        onClick={onClose}
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
      />
      <aside
        role="dialog"
        aria-label={`${slot.name} options`}
        className="relative z-10 flex h-full w-full max-w-lg flex-col overflow-y-auto border-l border-[var(--border,_#e2e8f0)] bg-[var(--bg-card,_var(--card,_#fff))] p-6 shadow-2xl"
      >
        <div className="mb-6">
          <p className="text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
            {page?.title || slot.page_id} · {slot.category || "uncategorized"}
          </p>
          <h3 className="text-2xl font-semibold">{slot.name}</h3>
          {slot.purpose_on_page && (
            <p className="mt-2 text-sm leading-relaxed text-[var(--fg-muted,_#64748b)]">
              {slot.purpose_on_page}
            </p>
          )}
        </div>

        {loading && (
          <p className="text-sm text-[var(--fg-muted,_#64748b)]">Loading catalog options…</p>
        )}

        {!loading && options && options.length === 0 && (
          <div className="mb-6 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-700 dark:text-amber-300">
            No master_components entries for category{" "}
            <code className="font-mono">{slot.category}</code>. The catalog is thin here.
            Skip with reason, or seed via <code className="font-mono">/ottomate seed-component</code>.
          </div>
        )}

        {!loading && options && options.length > 0 && (
          <ul className="mb-6 space-y-3">
            {options.map((opt) => (
              <li
                key={opt.id}
                className="rounded-2xl border border-[var(--border,_#e2e8f0)] bg-[var(--bg-elevated,_var(--stat-bg,_rgba(0,0,0,0.02)))] p-4"
              >
                <div className="mb-2 flex items-start justify-between gap-3">
                  <div>
                    <p className="font-medium">{opt.name}</p>
                    <p className="text-xs text-[var(--fg-muted,_#64748b)]">
                      {opt.framework_tags?.join(" · ") || "framework-agnostic"}
                    </p>
                  </div>
                  <button
                    disabled={busy != null}
                    onClick={() => pick(opt)}
                    className="rounded-full bg-[var(--accent-from,#6366f1)] px-3 py-1.5 text-xs font-medium text-white transition-opacity hover:opacity-90 disabled:opacity-50"
                  >
                    {busy === opt.id ? "Picking…" : "Pick this"}
                  </button>
                </div>
                {opt.description && (
                  <p className="text-xs leading-relaxed text-[var(--fg-muted,_#64748b)]">
                    {opt.description}
                  </p>
                )}
                {opt.preview_url ? (
                  <img
                    src={opt.preview_url}
                    alt={`${opt.name} preview`}
                    className="mt-3 max-h-48 w-full rounded-lg border border-[var(--border,_#e2e8f0)] object-cover"
                  />
                ) : (
                  <p className="mt-3 text-[11px] italic text-[var(--fg-muted,_#64748b)]">
                    No preview image. Source at{" "}
                    <code className="font-mono">{opt.source_code_path || "—"}</code>.
                  </p>
                )}
                {opt.tags && opt.tags.length > 0 && (
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {opt.tags.map((t) => (
                      <span
                        key={t}
                        className="rounded-full border border-[var(--border,_#e2e8f0)] px-2 py-0.5 text-[10px] text-[var(--fg-muted,_#64748b)]"
                      >
                        {t}
                      </span>
                    ))}
                  </div>
                )}
              </li>
            ))}
          </ul>
        )}

        {/* Skip box */}
        <div className="mb-4 rounded-2xl border border-[var(--border,_#e2e8f0)] bg-[var(--bg-elevated,_var(--stat-bg,_rgba(0,0,0,0.02)))] p-4">
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
            Skip this slot
          </p>
          <textarea
            value={skipReason}
            onChange={(e) => setSkipReason(e.target.value)}
            placeholder="Why skip? (e.g. custom-implementation, not-needed, defer-to-iteration)"
            className="mb-2 w-full rounded-lg border border-[var(--border,_#e2e8f0)] bg-[var(--bg-card,_var(--card,_#fff))] p-2 text-sm"
            rows={3}
          />
          <button
            disabled={busy != null}
            onClick={skip}
            className="rounded-full border border-amber-500/40 bg-amber-500/10 px-3 py-1.5 text-xs font-medium text-amber-700 hover:bg-amber-500/20 disabled:opacity-50 dark:text-amber-300"
          >
            {busy === "__skip__" ? "Skipping…" : "Skip with reason"}
          </button>
        </div>

        {error && (
          <div className="mb-4 rounded-xl border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-700 dark:text-rose-300">
            {error}
          </div>
        )}

        <button
          onClick={onClose}
          className="mt-auto rounded-full border border-[var(--border,_#e2e8f0)] px-4 py-2 text-sm font-medium hover:bg-[var(--bg-elevated,_var(--stat-bg,_rgba(0,0,0,0.02)))]"
        >
          Close
        </button>
      </aside>
    </div>
  );
}
