/**
 * /design — Ottomate per-project design surface.
 *
 * Server component. Fetches the project's UI master plan, slot list, and pages from the
 * tracker, then renders the static parts (header, tokens panel) and hands off interactive
 * parts (slot grid + drawer) to a client island.
 *
 * Visual language: BOTB pattern (rounded-2xl cards + top-edge gradient strip + restrained
 * fade/slide). Uses the project's OWN tokens via CSS vars, so each project's /design
 * matches its own brand.
 *
 * Generated by Ottomate skill scaffold.
 */
import { getDesignContext } from "@/lib/design/tracker";
import { DesignClient } from "./DesignClient";

export const dynamic = "force-dynamic";

export default async function DesignPage() {
  let ctx;
  try {
    ctx = await getDesignContext();
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    return (
      <main className="mx-auto max-w-5xl px-4 py-12 text-[var(--fg,_#0f172a)]">
        <div className="rounded-2xl border border-[color:var(--crit,_#ef4444)] bg-[color-mix(in_oklab,var(--crit,#ef4444)_10%,transparent)] p-6">
          <h1 className="mb-2 text-xl font-semibold">Couldn’t load /design</h1>
          <p className="mb-4 text-sm opacity-80">
            The tracker context-packet request failed. Check that the project is registered
            and the tracker is reachable.
          </p>
          <pre className="overflow-x-auto rounded-lg bg-black/30 p-3 font-mono text-xs">
            {msg}
          </pre>
        </div>
      </main>
    );
  }

  const { project, ui_master_plan, components, pages } = ctx;
  const pickedCount = components.filter((c) => c.picked === 1).length;
  const skippedCount = components.filter(
    (c) => c.picked === 0 && c.skip_reason != null
  ).length;
  const pendingCount = components.length - pickedCount - skippedCount;

  return (
    <main className="mx-auto max-w-6xl px-4 pt-6 pb-16">
      {/* Hero / header */}
      <header className="mb-8">
        <p className="mb-1 text-xs uppercase tracking-[0.18em] text-[var(--fg-muted,_#64748b)]">
          Ottomate · Design surface
        </p>
        <h1 className="text-3xl font-semibold tracking-tight">
          {project.display_name}{" "}
          <span className="text-[var(--fg-muted,_#64748b)]">/ design</span>
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-[var(--fg-muted,_#64748b)]">
          Visual reference + component pick surface for this project. Token strip,
          slot grid, drawer-based picks. Writes round-trip through the tracker.
        </p>
        <div className="mt-4 flex flex-wrap gap-2 text-xs">
          <StatusChip label="Total slots" value={components.length} tone="neutral" />
          <StatusChip label="Picked" value={pickedCount} tone="ok" />
          <StatusChip label="Skipped" value={skippedCount} tone="warn" />
          <StatusChip label="Pending" value={pendingCount} tone={pendingCount > 0 ? "crit" : "neutral"} />
          <StatusChip label="Pages" value={pages.length} tone="neutral" />
        </div>
      </header>

      {/* Tokens panel */}
      <TokensPanel ui={ui_master_plan} />

      {/* Slot grid + drawer (client island) */}
      <section className="mt-10">
        <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
          Component slots
        </h2>
        <DesignClient components={components} pages={pages} />
      </section>
    </main>
  );
}

function StatusChip({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone: "ok" | "warn" | "crit" | "neutral";
}) {
  const toneClass = {
    ok: "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300",
    warn: "border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-300",
    crit: "border-rose-500/30 bg-rose-500/10 text-rose-600 dark:text-rose-300",
    neutral:
      "border-[var(--border,_#e2e8f0)] bg-[var(--bg-elevated,_var(--card,_#fff))] text-[var(--fg-muted,_#64748b)]",
  }[tone];
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 ${toneClass}`}
    >
      <span className="font-medium">{value}</span>
      <span className="opacity-75">{label}</span>
    </span>
  );
}

function TokensPanel({ ui }: { ui: Awaited<ReturnType<typeof getDesignContext>>["ui_master_plan"] }) {
  const dark = ui.palette_dark ?? {};
  const light = ui.palette_light ?? {};
  const fonts = ui.fonts ?? {};
  return (
    <section className="relative overflow-hidden rounded-2xl border border-[var(--border,_#e2e8f0)] bg-[var(--bg-card,_var(--card,_#fff))] p-6">
      <span
        className="absolute top-0 right-6 left-6 h-[2px] rounded-full"
        style={{
          background: `linear-gradient(to right, var(--accent-from, #6366f1), var(--accent-to, #a855f7))`,
        }}
      />
      <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
        Master plan tokens
      </h2>
      <div className="grid gap-6 md:grid-cols-2">
        <PaletteBlock title="Dark palette" palette={dark} />
        <PaletteBlock title="Light palette" palette={light} />
      </div>
      <div className="mt-6 grid gap-2 text-sm md:grid-cols-3">
        <div>
          <p className="text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">Heading</p>
          <p style={{ fontFamily: fonts.heading || "inherit" }} className="text-lg">
            {fonts.heading || "(default sans)"}
          </p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">Body</p>
          <p style={{ fontFamily: fonts.body || "inherit" }} className="text-lg">
            {fonts.body || "(default sans)"}
          </p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">Mono</p>
          <p style={{ fontFamily: fonts.mono || "monospace" }} className="text-lg">
            {fonts.mono || "(default mono)"}
          </p>
        </div>
      </div>
      {ui.layout_style && (
        <div className="mt-6 rounded-xl border border-[var(--border,_#e2e8f0)] bg-[var(--bg-elevated,_var(--stat-bg,_rgba(0,0,0,0.02)))] p-3">
          <p className="mb-1 text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">
            Layout style
          </p>
          <p className="text-sm leading-relaxed">{ui.layout_style}</p>
        </div>
      )}
      {ui.animation_level && (
        <p className="mt-4 text-xs text-[var(--fg-muted,_#64748b)]">
          Animation level: <strong className="font-semibold">{ui.animation_level}</strong>
        </p>
      )}
    </section>
  );
}

function PaletteBlock({
  title,
  palette,
}: {
  title: string;
  palette: Record<string, string>;
}) {
  const entries = Object.entries(palette).filter(([k]) => !k.startsWith("_"));
  if (entries.length === 0) {
    return (
      <div>
        <p className="text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">{title}</p>
        <p className="mt-2 text-sm opacity-60">(no palette tokens)</p>
      </div>
    );
  }
  return (
    <div>
      <p className="mb-2 text-xs uppercase tracking-wider text-[var(--fg-muted,_#64748b)]">{title}</p>
      <div className="grid grid-cols-5 gap-2">
        {entries.map(([k, v]) => (
          <div key={k} className="group flex flex-col items-center">
            <span
              title={`${k} = ${v}`}
              className="block aspect-square w-full rounded-lg border border-[var(--border,_#e2e8f0)]"
              style={{ background: v }}
            />
            <span className="mt-1 max-w-full truncate text-[10px] text-[var(--fg-muted,_#64748b)]">
              {k.replace(/_/g, " ")}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
