/**
 * POST /api/design/pick
 *
 * Body: { component_id: number, asset_library_ref: string, variant?: string }
 *
 * Server-side proxy that round-trips the pick to the tracker with bearer auth.
 *
 * Generated by Ottomate skill scaffold.
 */
import { NextRequest, NextResponse } from "next/server";
import { pickComponent } from "@/lib/design/tracker";

export async function POST(req: NextRequest) {
  let body: { component_id?: number; asset_library_ref?: string; variant?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json body" }, { status: 400 });
  }
  const { component_id, asset_library_ref, variant } = body;
  if (typeof component_id !== "number" || !asset_library_ref) {
    return NextResponse.json(
      { error: "missing required fields: component_id (number), asset_library_ref (string)" },
      { status: 400 }
    );
  }
  try {
    const result = await pickComponent(component_id, asset_library_ref, variant);
    return NextResponse.json(result);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
